Preparing flexible header, adding Poppins font
R0galKJ/Movies-browser pull request #7
Opened 2023-10-03 22:55 UTC by gp231982

A flexible header for all devices was created, all comments have been removed, corrections of styling, "Poppins" font was added to HTML.

2023-10-04 15:19 UTC, R0galKJ requested changes

2023-10-04 15:19 UTC, R0galKJ commented on public/index.html
You can remove the font, it is already added.

2023-10-04 15:19 UTC, R0galKJ commented on src/common/Header/styled.js
Please add all breakpoint to theme and use by theme, colors too.

2023-10-04 16:33 UTC, gp231982 commented on public/index.html
I've tried to add it to GlobalStyles but from some reason It did not work for me... that is why I've added it to GlobalStyle. I'll try again.

2023-10-04 16:39 UTC, gp231982 commented on src/common/Header/styled.js
Ok, clear. Let You know when finished.

2023-10-08 18:47 UTC, gp231982 commented on src/common/Header/styled.js
Changes will be added later acc. to agreements

2023-10-08 18:47 UTC, KamilJustynski approved these changes

2023-10-08 18:47 UTC, KamilJustynski commented on src/common/Header/styled.js
ok

2023-10-08 18:48 UTC, merged